version: '3'

services:
  web:
    image: ill-contain
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data:
